### ISSUE TITLE
Launcher window not fully visible

### ISSUE THREAD

**Issue by mmalyska** [nokka/slashdiablo-launcher#3]
Hi, when I start the launcher, the window is not fully visible na it launches as full screen. 
Here is screenshot of my whole screen:
![obraz](https://user-images.githubusercontent.com/999598/141975618-9e84a63f-2e00-4155-80d9-f3e7c1cc0d29.png)

My screen is in resolution 1920x1080 and the scaling I have set to 150%
![obraz](https://user-images.githubusercontent.com/999598/141975909-f1d628d6-d7bd-4238-aa13-fc017e2661a2.png)

**Comment by nokka** [comment]
Hi! Yes this is a known issue unfortunately, it has to do with the dpi scaling, basically Windows tries to scale it to 150%  which unfortunately does not work well. I will need to try and reproduce this and see if it's fixable with the underlying library we're using to drawn the window.

Only fix I have for you right now is to use 100% dpi scaling and it should work, but that will probably impact the rest of your experience on your machine negatively.

**Comment by mmalyska** [comment]
I have found solution for this in compatibility setting. Now app scales normally.
![obraz](https://user-images.githubusercontent.com/999598/142161200-a4217523-2daf-4275-ad6d-666f53781a96.png)
